<?php
// The ID using the code on the UL is important - this is what Magento will use to hide and display the 
// Form with javascript - it should be set to display:none by default
$_code = $this->getMethod()->getCode();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
</ul>

<script type="text/javascript">
    //<![CDATA[
    var oReq = new XMLHttpRequest();
    oReq.open('get', '<?php echo $this->host; ?>/fintecture/standard/checkoutstats', true);
    oReq.send();
    //]]>
</script>